### ISSUE TITLE
All of your Spartan Weaponry addons need updates for the latest build of Spartan Weaponry

### ISSUE THREAD

**Issue by Sunconure11** [ChaosBuffalo/SpartanFire#1]
As it currently stands, the newest build of Spartan Weaponry breaks compatibility with your addons.

**Comment by Sunconure11** [comment]
![screenshot 2018-08-20 16 12 39](https://user-images.githubusercontent.com/5614902/44364029-ec83ab80-a493-11e8-9ca7-98ab7ab94bb7.png)
@Kovak

**Comment by Kovak** [comment]
I'm aware.

New versions are in the works, there was a decent bit of changes to Spartan Weaponry, this is why we locked Spartan Fire to a specific version of Spartan Weaponry.

**Comment by Sunconure11** [comment]
There appears to be a new build of Spartan Weaponry with a new build of it's API.

**Comment by Voxel-Friend** [comment]
Is this still going to be handled any time soon? No rush, but was hoping to have it on our server.

**Comment by Sunconure11** [comment]
All of the addons are MIT and could probably be picked up

**Comment by Sunconure11** [comment]
@Voxel-Friend Ping me through here when you're going to tackle those addons.

**Comment by Kovak** [comment]
@Voxel-Friend and @Sunconure11 I have some local work on this particular mod on my pc that I will upload this weekend.

**Comment by Kovak** [comment]
Just published an updated version of Spartan and Fire to curseforge.

**Comment by Sunconure11** [comment]
Any work on the other plugins? They should get some updating too.

**Comment by Kovak** [comment]
I think we may be dropping a few of those mods in our own modpack so I'm not certain if I will maintain them all. I'll probably get around to updating the better with mods one at some point.

**Comment by Trinsdar** [comment]
So far I've updated soartan bm and released it seperatly.

**Comment by Kovak** [comment]
@Trinsdar did you release it on curse forge under a new name?

**Comment by Trinsdar** [comment]
Yes: https://minecraft.curseforge.com/projects/base-metals-weaponry

**Comment by Trinsdar** [comment]
And I've just finished fixing an issue with spartan fire tonight

**Comment by Trinsdar** [comment]
Also is there any reason why spartanlands code isn't released on github?

**Comment by Kovak** [comment]
I probably just forgot to upload it. I'll get that taken care of.

**Comment by Sunconure11** [comment]
New update came out. Might want to check compatibility.

**Comment by Sunconure11** [comment]
@Kovak Have you been on at all lately?

**Comment by Sunconure11** [comment]
Also, Ice and Fire is adding at least one new material for tools/weapons in it's next update. You might want to add support for it when it comes.

**Comment by Sunconure11** [comment]
This may no longer be compatible with the latest build
