### ISSUE TITLE
Weapons from this tend to become OP fast

### ISSUE THREAD

**Issue by Sunconure11** [ChaosBuffalo/SpartanFire#5]
Users won't stop complaining to me about the severe imbalance so

https://cdn.discordapp.com/attachments/547111527899988100/616680443546173472/Screenshot_17.png

Here's an example of the damage rates from one of the weapons

**Comment by Kovak** [comment]
On my server we use a combo of the spartan weaponry and the ice and fire config files to tone down the damage. This mod takes the values directly from the parent mod configs so it's not something we set ourselves.
