### ISSUE TITLE
1.12.2 Server Crashes after Ice and Fire Update

### ISSUE THREAD

**Issue by threeringserkus** [ChaosBuffalo/SpartanFire#7]
https://pastebin.com/5BPv5h6z

Forge 14.23.5.2847

Bless

**Comment by threeringserkus** [comment]
Issue appears to have spontaneously resolved itself. I literally did nothing and it just decided that it would realize I'd updated both mods???

**Comment by democat3457** [comment]
¯\\\_(ツ)_/¯ It's a generic Minecraft error. Not sure if it was related?
