### ISSUE TITLE
Spartan and fire 1.16.4 ? (not so much a complaint)

### ISSUE THREAD

**Issue by SpudCast** [ChaosBuffalo/SpartanFire#8]
is there an update for 1.16.4 coming anytime soon with the new lightning dragon weaponry ?

**Comment by SpudCast** [comment]
or even just for the fire and ice dragons because the spartan weapons are my favourite weapons to use

**Comment by democat3457** [comment]
probably not anytime soon, but another person might try and pick it up

**Comment by minhtet-htoon** [comment]
> probably not anytime soon, but another person might try and pick it up

So, it's fine if I port this to 1.16 as a separate project? If so, can I use the textures that you guys have already made?

**Comment by democat3457** [comment]
@Kovak ^
